set_property SRC_FILE_INFO {cfile:/home/chenxun/Documents/Project/FPGA_Network/src_vivado/PCIe_Vivado_Project.srcs/constrs_1/new/PCIe_constraint.xdc rfile:../../../PCIe_Vivado_Project.srcs/constrs_1/new/PCIe_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports i_pcie_refclkp]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC16 [get_ports o_led0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC18 [get_ports i_pcie_rstn]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD18 [get_ports i_clk_ila]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports {i_pcie_rxp[0]}]
